version: '3.1'

# services = containers
services:

  db: 
    build: ./db
    restart: always # default=no / on-failure / always
    environment:
      MYSQL_ROOT_PASSWORD: 123456 # similar to docker run -e MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./database:/var/lib/mysql

  adminer:
    build: ./adminer
    restart: always
    ports:
      - 8087:8080 # local:internal ports
