version: '3.1'

# services = containers
services:

  db: 
    image: mariadb
    restart: always # default=no / on-failure / always
    environment:
      MYSQL_ROOT_PASSWORD: 123456 # similar to docker run -e MYSQL_ROOT_PASSWORD=example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8087:8080 # local:internal ports
